import { describe, expect, it } from 'vitest';
import { buildEnvContent, backupFileName } from './setup-lib.js';

describe('setup: backup file naming', () => {
  it('produces .env.backup.YYYYMMDDTHHMMSS format', () => {
    const name = backupFileName();
    expect(name).toMatch(/^\.env\.backup\.\d{8}T\d{6}$/);
  });

  it('uses the provided date', () => {
    const name = backupFileName(new Date('2026-02-11T14:30:22.000Z'));
    expect(name).toBe('.env.backup.20260211T143022');
  });
});

describe('setup: .env content generation', () => {
  it('includes required values', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      DISCOCLAW_TASKS_FORUM: '111111111111111111',
      DISCOCLAW_CRON_FORUM: '222222222222222222',
    });
    expect(content).toContain('DISCORD_TOKEN=abc.def.ghi');
    expect(content).toContain('DISCORD_ALLOW_USER_IDS=12345678901234567');
    expect(content).toContain('DISCOCLAW_TASKS_FORUM=111111111111111111');
    expect(content).toContain('DISCOCLAW_CRON_FORUM=222222222222222222');
  });

  it('maps legacy DISCOCLAW_BEADS_FORUM input to DISCOCLAW_TASKS_FORUM output', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      DISCOCLAW_BEADS_FORUM: '111111111111111111',
      DISCOCLAW_CRON_FORUM: '222222222222222222',
    });
    expect(content).toContain('DISCOCLAW_TASKS_FORUM=111111111111111111');
    expect(content).not.toContain('DISCOCLAW_BEADS_FORUM=');
  });

  it('includes core values when provided (backward-compat: no PRIMARY_RUNTIME)', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      DISCORD_GUILD_ID: '98765432109876543',
      CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS: '1',
      CLAUDE_OUTPUT_FORMAT: 'stream-json',
    });
    expect(content).toContain('DISCORD_GUILD_ID=98765432109876543');
    expect(content).toContain('CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS=1');
    expect(content).toContain('CLAUDE_OUTPUT_FORMAT=stream-json');
    expect(content).toContain('# CORE');
    expect(content).not.toContain('# PROVIDER');
  });

  it('Claude provider path places PRIMARY_RUNTIME and Claude vars in # PROVIDER, not # CORE', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      PRIMARY_RUNTIME: 'claude',
      CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS: '1',
      CLAUDE_OUTPUT_FORMAT: 'stream-json',
    });
    expect(content).toContain('PRIMARY_RUNTIME=claude');
    expect(content).toContain('CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS=1');
    expect(content).toContain('CLAUDE_OUTPUT_FORMAT=stream-json');
    expect(content).toContain('# PROVIDER');
    expect(content).not.toContain('# CORE');
  });

  it('includes optional values when provided', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      DISCOCLAW_TASKS_FORUM: '111111111111111111',
      DISCOCLAW_CRON_FORUM: '222222222222222222',
      DISCOCLAW_DISCORD_ACTIONS: '1',
      DISCOCLAW_STATUS_CHANNEL: 'status',
    });
    expect(content).toContain('DISCOCLAW_DISCORD_ACTIONS=1');
    expect(content).toContain('DISCOCLAW_STATUS_CHANNEL=status');
  });

  it('omits optional section when no optional values', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    expect(content).not.toContain('# OPTIONAL');
  });

  it('includes reference to .env.example.full', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    expect(content).toContain('.env.example.full');
  });

  it('includes generated-by header and timestamp', () => {
    const ts = new Date('2026-02-11T12:00:00.000Z');
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    }, ts);
    expect(content).toContain('generated by pnpm setup');
    expect(content).toContain('Created: 2026-02-11T12:00:00.000Z');
  });

  it('omits core section when no core values are set', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    expect(content).not.toContain('# CORE');
  });

  it('includes PRIMARY_RUNTIME and Gemini values when provided', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      PRIMARY_RUNTIME: 'gemini',
      GEMINI_BIN: 'gemini',
      GEMINI_MODEL: 'gemini-2.5-pro',
    });
    expect(content).toContain('PRIMARY_RUNTIME=gemini');
    expect(content).toContain('GEMINI_BIN=gemini');
    expect(content).toContain('GEMINI_MODEL=gemini-2.5-pro');
  });

  it('includes PRIMARY_RUNTIME and OpenAI key when provided', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      PRIMARY_RUNTIME: 'openai',
      OPENAI_API_KEY: 'sk-test-key',
    });
    expect(content).toContain('PRIMARY_RUNTIME=openai');
    expect(content).toContain('OPENAI_API_KEY=sk-test-key');
  });

  it('includes PRIMARY_RUNTIME and Codex values when provided', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      PRIMARY_RUNTIME: 'codex',
      CODEX_BIN: '/usr/local/bin/codex',
      CODEX_MODEL: 'codex-latest',
      CODEX_DANGEROUSLY_BYPASS_APPROVALS_AND_SANDBOX: '1',
    });
    expect(content).toContain('PRIMARY_RUNTIME=codex');
    expect(content).toContain('CODEX_BIN=/usr/local/bin/codex');
    expect(content).toContain('CODEX_MODEL=codex-latest');
    expect(content).toContain('CODEX_DANGEROUSLY_BYPASS_APPROVALS_AND_SANDBOX=1');
  });
});

describe('setup: atomic write design', () => {
  it('buildEnvContent produces valid .env syntax (KEY=VALUE per line)', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    const dataLines = content.split('\n').filter((l) => l && !l.startsWith('#'));
    for (const line of dataLines) {
      expect(line).toMatch(/^[A-Z_]+=.*/);
    }
  });
});
