/**
 * Pure helper functions for the setup wizard.
 * Extracted so tests can import them without triggering the interactive flow.
 */

/** Generate a timestamped backup filename. */
export function backupFileName(now = new Date()): string {
  const ts = now.toISOString().replace(/[-:]/g, '').replace(/\.\d+Z$/, '');
  return `.env.backup.${ts}`;
}

/** Build .env file content from a key-value map. */
export function buildEnvContent(vals: Record<string, string>, now = new Date()): string {
  const lines: string[] = [
    '# Discoclaw — generated by pnpm setup',
    `# Created: ${now.toISOString()}`,
    '',
  ];

  // Required
  lines.push('# REQUIRED');
  lines.push(`DISCORD_TOKEN=${vals.DISCORD_TOKEN ?? ''}`);
  lines.push(`DISCORD_ALLOW_USER_IDS=${vals.DISCORD_ALLOW_USER_IDS ?? ''}`);
  lines.push(`DISCOCLAW_BEADS_FORUM=${vals.DISCOCLAW_BEADS_FORUM ?? ''}`);
  lines.push(`DISCOCLAW_CRON_FORUM=${vals.DISCOCLAW_CRON_FORUM ?? ''}`);
  lines.push('');

  // Core
  const coreKeys = [
    'DISCORD_GUILD_ID',
    'PRIMARY_RUNTIME',
    'CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS',
    'CLAUDE_OUTPUT_FORMAT',
    'GEMINI_BIN',
    'GEMINI_MODEL',
    'OPENAI_API_KEY',
    'CODEX_BIN',
    'CODEX_MODEL',
    'CODEX_BYPASS_APPROVALS',
  ];
  const hasCore = coreKeys.some((k) => vals[k]);
  if (hasCore) {
    lines.push('# CORE');
    if (vals.DISCORD_GUILD_ID) lines.push(`DISCORD_GUILD_ID=${vals.DISCORD_GUILD_ID}`);
    if (vals.PRIMARY_RUNTIME) lines.push(`PRIMARY_RUNTIME=${vals.PRIMARY_RUNTIME}`);
    if (vals.CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS) lines.push(`CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS=${vals.CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS}`);
    if (vals.CLAUDE_OUTPUT_FORMAT) lines.push(`CLAUDE_OUTPUT_FORMAT=${vals.CLAUDE_OUTPUT_FORMAT}`);
    if (vals.GEMINI_BIN) lines.push(`GEMINI_BIN=${vals.GEMINI_BIN}`);
    if (vals.GEMINI_MODEL) lines.push(`GEMINI_MODEL=${vals.GEMINI_MODEL}`);
    if (vals.OPENAI_API_KEY) lines.push(`OPENAI_API_KEY=${vals.OPENAI_API_KEY}`);
    if (vals.CODEX_BIN) lines.push(`CODEX_BIN=${vals.CODEX_BIN}`);
    if (vals.CODEX_MODEL) lines.push(`CODEX_MODEL=${vals.CODEX_MODEL}`);
    if (vals.CODEX_BYPASS_APPROVALS) lines.push(`CODEX_BYPASS_APPROVALS=${vals.CODEX_BYPASS_APPROVALS}`);
    lines.push('');
  }

  // Optional
  const optionalKeys = [
    'DISCOCLAW_DISCORD_ACTIONS',
    'DISCOCLAW_STATUS_CHANNEL',
  ];
  const hasOptional = optionalKeys.some((k) => vals[k]);
  if (hasOptional) {
    lines.push('# OPTIONAL');
    for (const k of optionalKeys) {
      if (vals[k]) lines.push(`${k}=${vals[k]}`);
    }
    lines.push('');
  }

  lines.push('# For all options, see .env.example.full');
  lines.push('');

  return lines.join('\n');
}
